### ISSUE TITLE
Create an official, Automated Build image on Docker Hub

### ISSUE THREAD

**Issue by pataquets** [johnlpage/POCDriver#19]
Docker Hub allows you to create Automated Builds from source: https://docs.docker.com/docker-hub/builds/
It would add another packaging/distribution/installation method, whose buildings would be triggered automatically on each commit. It also allows to create different image tags from git tags & branches.
Also, documentation could easily include a canonical `docker run` statement to quickly spin up a POCDriver instance with just a single command.

By making the image build via an AB, you give the resulting image verifiability and auditability. Also, the build is fully automatic. You can have the latest image tag build from HEAD and individual image tags from git's release tags.
Some people avoid non-verifiable (manually uploaded) images due to security & traceability reasons.

Docker search command clearly displays AB when listing images:
```
$ docker search pocdriver
NAME                  DESCRIPTION   STARS     OFFICIAL   AUTOMATED
pataquets/pocdriver   POCDriver     0                    [OK]
manfontan/pocdriver                 0                    
```
Just a free Docker Hub account and a quick setup would do. Ping me if you need help.

**Comment by pataquets** [comment]
@johnlpage : Ping? Let me know if I can be of any help.

**Comment by manfontan** [comment]
@igalrivin  do you want to look at this?

**Comment by pataquets** [comment]
@johnlpage @igalrivin ping

**Comment by pataquets** [comment]
@johnlpage While I was doing a bit of spring cleaning on my GitHub repos, I've found my fork of POCDriver. I forked it to setup a Docker Hub Automated Build to use POCDriver from Docker.
I've not used it a lot, but my public Docker image has +8.6K pulls! I don't have a clue who can be using it so much (in production?), but they have been using a quite outdated version, since I've not pulled upstream since the OP. I have pulled upstream HEAD and pushed to my fork and the Docker Hub AB still builds.
Also, another image has appeared on Docker Hub.

Looking at the readme, I see no install artifact, so possible users are left only with the build-it-yourself route. It would be safer not to depend on my non-official. unmaintained image to get a quick test drive. Also, it won't have all the latest features, sadly.

**Comment by johnlpage** [comment]
Will not consider using or supporting docker under any circumstances.

**Comment by pataquets** [comment]
Fair enough. Sorry to hear that, @johnlpage. Of course, it's your choice.
Out of curiosity, I wonder which reason(s) led you to that? Maintainability? Not using Docker? Permissions? (I've encountered a few devs who are not confortable linking or giving Docker Hub access to their Github repos, which is fine). Just looking for another developer's PoV.

Although I no longer use POCDriver, if there is something I can do to help, do not hesitate to ask for it, and thanks for sharing this software, anyway.

**Comment by utdrmac** [comment]
@johnlpage has you attitude towards docker/podman changed in the past 4 years? It would be really great to see a docker container for this instead of having to compile it each time we want to deploy a new infra.
