### ISSUE TITLE
Add a way to specify a custom shard key

### ISSUE THREAD

**Issue by niccottrell** [johnlpage/POCDriver#33]

**Comment by niccottrell** [comment]
The current _id is not a great shard key, but then other options like the default fld0 isn't great either. Based on testing by @josefahmad the values don't seem to be properly random.

**Comment by josefahmad** [comment]
Attaching the [plot_split_distribution](https://github.com/josefahmad/mongo-shardkey-tools) output for `_id: 1` as the shard key (default), and for `fld0: 1`respectively. Looks like `fld0` is not truly random.

![shard_on_id](https://user-images.githubusercontent.com/29626682/53504791-df82ed00-3ab2-11e9-8dbc-e6c7014aa478.png)
![shard_on_fld0](https://user-images.githubusercontent.com/29626682/53504798-e27ddd80-3ab2-11e9-9f50-443d2fe48261.png)

I think we can pick a default shard key with better distribution.

**Comment by johnlpage** [comment]
@josefahmad - the shard key in POCdriver is explicitly designed and chosen to be optimal - unlike a random shard key which is inherently bad it is supposed to be monotonically increasing from a low cardinality set of seed points. POCDriver was actually designed initially to demonstrate this principle.
 The shard key is optimal for writing and also supporting the internal mechanisms of POCDriver.
