### ISSUE TITLE
Query on POCDriver

### ISSUE THREAD

**Issue by bhargavait** [johnlpage/POCDriver#7]
This is no an issue.. I have query regarding the tool.. If I ran the insert only operation(java -jar POCDriver.jar -i 100 -d 600)  for 10mins, Does the POCDriver loads the records continuously ? 

In my test run after few seconds I see the no records are getting loaded and start loading after sometime.. Is this an expected behaviour?

After 140 seconds, 2451968 new records inserted - collection has 23130882 in total
23654 inserts per second since last report 87.05 % in under 50 milliseconds
0 keyqueries per second since last report 100.00 % in under 50 milliseconds
0 updates per second since last report 100.00 % in under 50 milliseconds
0 rangequeries per second since last report 100.00 % in under 50 milliseconds

------------------------
After 150 seconds, 2451968 new records inserted - collection has 23130882 in total
0 inserts per second since last report 87.05 % in under 50 milliseconds
0 keyqueries per second since last report 100.00 % in under 50 milliseconds
0 updates per second since last report 100.00 % in under 50 milliseconds
0 rangequeries per second since last report 100.00 % in under 50 milliseconds
...
After 190 seconds, 2540032 new records inserted - collection has 23218946 in total
8806 inserts per second since last report 86.92 % in under 50 milliseconds
0 keyqueries per second since last report 100.00 % in under 50 milliseconds
0 updates per second since last report 100.00 % in under 50 milliseconds
0 rangequeries per second since last report 100.00 % in under 50 milliseconds

**Comment by johnlpage** [comment]
it's quite possible that MongoDB, especially with WiredTiger is stalling whilst it flushes to disk at that point, talk to MongoDB support about tuning the cache size. cache eviction threads and testing the disk speed to fix it. But yes, POCDriver is supposed to be constantly writing.

**Comment by bhargavait** [comment]
For POCDriver, What could be the minimum CPU and RAM requirements?

**Comment by johnlpage** [comment]
Minimum is determined by how much load you want to generate. It will run
with 1 CPU but that cannot drive enough load for most servers. Typically
1:1 Client to Server hardware ratio is used.

**Comment by johnlpage** [comment]
It needs enough ram to hold DocumentSize (use -p to see this) x numThreads
x BatchSize , default is 2x4x512 KB

**Comment by bhargavait** [comment]
Have you tested the POCDriver.jar on rhel running on IBM Power system? Does this jar contains any functions specific to x86?

**Comment by johnlpage** [comment]
Not tested on power but nothing X86 specific
