### ISSUE TITLE
Multiple Java POCDriver client on the same MongoDB engine

### ISSUE THREAD

**Issue by jlimodinFR** [johnlpage/POCDriver#8]
Hello, 
For a scalability issue, I would like to launch multiple POCDriver java clients on the same MongoDB engine. 
Unfortunately, I have this error on the 2nd POCDriver client I launched: 
"state should be: writes is not an empty list"
Is your app designed to be launched multiple time on the same MongoDB ? 
Thanks
Julien

**Comment by johnlpage** [comment]
Yes, each thread needs a unique ID though regardless of machine so use
 --threadIdStart <arg> 

TO set a unique starting point on each server.
